name = "dynablocksdev" # Your project name
main = "index.js"
compatibility_date = "2025-07-06" # Use a recent compatibility date

[[durable_objects.bindings]]
name = "WEBSOCKET_DURABLE_OBJECT"
class_name = "WebSocketDurableObject"
# To ensure compatibility with Cloudflare Pages Functions,
# the 'script_name' should be omitted if the Durable Object class
# (WebSocketDurableObject) is defined within the Pages Function itself.
# This binding will then refer to the Durable Object class
# exposed by the current Pages Function.
